# Generated by Django 5.0.4 on 2024-04-22 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_remove_user_ismanager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='dimension_x',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dimension_y',
        ),
        migrations.RemoveField(
            model_name='item',
            name='dimension_z',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
            preserve_default=False,
        ),
    ]
