# Generated by Django 5.0.4 on 2024-04-23 14:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remove_item_dimension_x_remove_item_dimension_y_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='site',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='app.site'),
            preserve_default=False,
        ),
    ]
