# Generated by Django 4.2 on 2024-06-09 01:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_user_is_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_manager',
        ),
    ]
